source 'https://supermarket.chef.io'

# including all dependencies from metadata causes berks to fail
# due to a know issue with berkshelf. please list berkshelf
# dependencies here explicitly
#metadata
